#!/bin/bash
# Self-host the three brand fonts (constitution: no third-party font
# CDNs at runtime). Downloads latin woff2 subsets from Google Fonts
# ONCE into public/fonts/ and writes src/styles/fonts.css with local
# @font-face rules. Reproducible: safe to re-run, overwrites in place.
set -euo pipefail
cd "$(dirname "$0")/.."
UA="Mozilla/5.0 (Macintosh) AppleWebKit/537.36 Chrome/120 Safari/537.36"
CSS_URL='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Newsreader:ital,opsz,wght@0,6..72,300..700;1,6..72,300..600&family=JetBrains+Mono:wght@400;500&display=swap'
curl -fsS -A "$UA" "$CSS_URL" -o /tmp/gf.css
python3 - <<'PY'
import re, urllib.request, pathlib
css = open('/tmp/gf.css').read()
# keep only latin (not latin-ext) blocks
blocks = re.findall(r'/\* ([a-z-]+) \*/\s*(@font-face \{[^}]+\})', css)
out, n = [], 0
for subset, block in blocks:
    if subset != 'latin':
        continue
    url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
    fam = re.search(r"font-family: '([^']+)'", block).group(1).replace(' ', '')
    style = re.search(r'font-style: (\w+)', block).group(1)
    weight = re.search(r'font-weight: ([\d ]+)', block).group(1).replace(' ', '-')
    name = f'{fam}-{weight}-{style}.woff2'
    urllib.request.urlretrieve(url, f'public/fonts/{name}')
    block = block.replace(url, f'/fonts/{name}')
    # JetBrains Mono renders long code blocks; a late swap reflows them
    # (measured CLS 0.214 on the quickstart). optional = no swap, no shift.
    if fam == 'JetBrainsMono':
        block = block.replace('font-display: swap;', 'font-display: optional;')
    out.append(block)
    n += 1
pathlib.Path('src/styles/fonts.css').write_text(
    '/* GENERATED by scripts/fetch-fonts.sh; self-hosted latin subsets */\n'
    + '\n'.join(out) + '\n')
print(f'fonts: {n} latin woff2 files -> public/fonts/, fonts.css written')
PY
